--
-- RagnarokOnline Settings File
-- Generated by RagnarokOnline OpenSetup, Version 2.14.1.425 ( http://ai4rei.net/p/opensetup )
--

-- Workaround for people with broken client folder
-- Note: The client removes this when it saves settings.
--
if OptionInfoList==nil then
	OptionInfoList = {}
end
if CmdOnOffList==nil then
	CmdOnOffList = {}
end
-- End of Workaround


-- Settings
--

OptionInfoList["Trilinear"] = 0
OptionInfoList["Bgm_Volume"] = 20
OptionInfoList["Effect_Volume"] = 6
OptionInfoList["MouseExclusive"] = 0
OptionInfoList["ISFULLSCREENMODE"] = 0
OptionInfoList["WIDTH"] = 640
OptionInfoList["HEIGHT"] = 480
OptionInfoList["BITPERPIXEL"] = 16
OptionInfoList["DEVICECNT"] = 2
OptionInfoList["MODECNT"] = 0
OptionInfoList["SPRITEMODE"] = 2
OptionInfoList["TEXTUREMODE"] = 2
CmdOnOffList["/bgm"] = 0
CmdOnOffList["/sound"] = 0
CmdOnOffList["/notrade"] = 0
CmdOnOffList["/noshift"] = 1
CmdOnOffList["/noctrl"] = 1
CmdOnOffList["/skillfail"] = 1
CmdOnOffList["/notalkmsg"] = 0
CmdOnOffList["/notalkmsg2"] = 0
CmdOnOffList["/showname"] = 1
CmdOnOffList["/fog"] = 0
CmdOnOffList["/aura"] = 1
CmdOnOffList["/window"] = 1
CmdOnOffList["/miss"] = 1
CmdOnOffList["/effect"] = 1
CmdOnOffList["/shopping"] = 1
CmdOnOffList["/stateinfo"] = 1
CmdOnOffList["/loginout"] = 1
CmdOnOffList["/snap"] = 0
CmdOnOffList["/itemsnap"] = 0
CmdOnOffList["/skillsnap"] = 1
CmdOnOffList["/camera"] = 0
CmdOnOffList["/hoai"] = 1
CmdOnOffList["/merai"] = 1
CmdOnOffList["/lightmap"] = 0
CmdOnOffList["/monsterhp"] = 1
CmdOnOffList["/q1"] = 0
CmdOnOffList["/q2"] = 0
CmdOnOffList["/aura2"] = 0
CmdOnOffList["/btg"] = 1
CmdOnOffList["/cashshop"] = 1
CmdOnOffList["/goldpc"] = 1
CmdOnOffList["/roulette"] = 1
CmdOnOffList["/quake"] = 1

-- Preserved client settings
--

OptionInfoList["OLD_WIDTH"] = 1024
OptionInfoList["ChangeChatMode"] = 1
OptionInfoList["bBlockPrivateTab"] = 1
OptionInfoList["bSoundEffectInItemSellWnd"] = 0
OptionInfoList["bItemDefaultSort"] = 1
OptionInfoList["ChannelCopID"] = 0
OptionInfoList["Window_XPos"] = 128
OptionInfoList["LockMouse"] = 0
OptionInfoList["Outdoor_ViewLatitude"] = -50
OptionInfoList["Indoor_ViewDistance"] = 300
OptionInfoList["bWarningPriceCheck"] = 0
OptionInfoList["/zoom"] = 1
OptionInfoList["bShowMenuIcon"] = 1
OptionInfoList["AutoOpen1to1Window"] = 0
OptionInfoList["bGuildMemberListSort"] = 1
OptionInfoList["AutoOpen1to1Window_Friend"] = 0
OptionInfoList["ShowBattleFieldIcon"] = 1
OptionInfoList["Simplicity_SkillList"] = 0
OptionInfoList["bItemAscendingOrder"] = 0
OptionInfoList["Outdoor_ViewDistance"] = 451.500183
OptionInfoList["Window_YPos"] = 0
OptionInfoList["SkinName"] = "aliceinwonderland"
OptionInfoList["Show_SkillDescript"] = 1
OptionInfoList["PlaySound_Open1to1Window"] = 0
OptionInfoList["Emblem Frame"] = 0
OptionInfoList["Indoor_ViewLatitude"] = -45
OptionInfoList["bLockItemDropFromItemWnd"] = 0
OptionInfoList["OLD_HEIGHT"] = 768
OptionInfoList["bItemDescendingOrder"] = 0
CmdOnOffList["/mable"] = 1
CmdOnOffList["/minimap"] = 1
CmdOnOffList["/mineffect"] = 0
CmdOnOffList["/zoom"] = 1
