MyTact={}
MyTact[0]={TACT_ATTACK_H,SKILL_ALWAYS,KITE_REACT,CAST_REACT,PUSH_NEVER,DEBUFF_NEVER,CLASS_BOTH,RESCUE_ALL,-1,SNIPE_OK,KS_POLITE,1,CHASE_ALWAYS} --Default
TactLastSavedDate        = "9/28/2023 2:46:10 PM"